config/routes.rb
Rails.application.routes.draw do
  resources :status_data
  resources :verifikators
  resources :aplikasis
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'aplikasis#index'
end

app/models/aplikasi.rb
class Aplikasi < ApplicationRecord
has_many :verifikators
def to_s
    nama
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/status_datum.rb
class StatusDatum < ApplicationRecord
end

app/models/verifikator.rb
class Verifikator < ApplicationRecord
    has_many :aplikasis

    require 'csv'

belongs_to :aplikasi

    def self.to_csv
        CSV.generate(col_sep: ";") do |csv|
            csv << attribute_names
            #csv << column_names
            all.each do |record|
                csv << record.attributes.values
            end
        end
    end
end

app/controllers/aplikasis_controller.rb
class AplikasisController < ApplicationController
  before_action :set_aplikasi, only: %i[show edit update destroy]

  # GET /aplikasis or /aplikasis.json
  def index
    @aplikasis = Aplikasi.all
  end

  # GET /aplikasis/1 or /aplikasis/1.json
  def show; end

  # GET /aplikasis/new
  def new
    @aplikasi = Aplikasi.new
  end

  # GET /aplikasis/1/edit
  def edit; end

  # POST /aplikasis or /aplikasis.json
  def create
    @aplikasi = Aplikasi.new(aplikasi_params)

    if @aplikasi.save
      respond_to do |format|
        format.html { redirect_to aplikasi_url(@aplikasi), notice: 'Aplikasi was successfully created.' }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /aplikasis/1 or /aplikasis/1.json
  def update
    respond_to do |format|
      if @aplikasi.update(aplikasi_params)
        format.html { redirect_to aplikasi_url(@aplikasi), notice: 'Aplikasi was successfully updated.' }
        format.json { render :show, status: :ok, location: @aplikasi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aplikasi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aplikasis/1 or /aplikasis/1.json
  def destroy
    @aplikasi.destroy!

    respond_to do |format|
      format.html { redirect_to aplikasis_url, notice: 'Aplikasi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_aplikasi
    @aplikasi = Aplikasi.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def aplikasi_params
    params.require(:aplikasi).permit(:nama, :alamat_web, :nama_penanggung_jawab, :deskripsi)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/status_data_controller.rb
class StatusDataController < ApplicationController
  before_action :set_status_datum, only: %i[ show edit update destroy ]

  # GET /status_data or /status_data.json
  def index
    @status_data = StatusDatum.all
  end

  # GET /status_data/1 or /status_data/1.json
  def show
  end

  # GET /status_data/new
  def new
    @status_datum = StatusDatum.new
  end

  # GET /status_data/1/edit
  def edit
  end

  # POST /status_data or /status_data.json
  def create
    @status_datum = StatusDatum.new(status_datum_params)

    respond_to do |format|
      if @status_datum.save
        format.html { redirect_to status_datum_url(@status_datum), notice: "Status data was successfully created." }
        format.json { render :show, status: :created, location: @status_datum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_data/1 or /status_data/1.json
  def update
    respond_to do |format|
      if @status_datum.update(status_datum_params)
        format.html { redirect_to status_datum_url(@status_datum), notice: "Status data was successfully updated." }
        format.json { render :show, status: :ok, location: @status_datum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_data/1 or /status_data/1.json
  def destroy
    @status_datum.destroy!

    respond_to do |format|
      format.html { redirect_to status_data_url, notice: "Status data was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_datum
      @status_datum = StatusDatum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_datum_params
      params.require(:status_datum).permit(:kondisi_data, :catatan, :rekomendasi, :validasi)
    end
end

app/controllers/verifikators_controller.rb
class VerifikatorsController < ApplicationController
  before_action :set_verifikator, only: %i[ show edit update destroy ]

  
  # GET /verifikators or /verifikators.json
  def index
    @verifikators = Verifikator.all
    respond_to do |format|
      format.html
      format.csv do#{ send_data ExportVerifikatorCSVService.new(@verifikators).generate }
        send_data Verifikator.to_csv, filename: "verifikator.csv"
    end
  end
end
  # GET /verifikators/1 or /verifikators/1.json
  def show
  end

  # GET /verifikators/new 
  def new
    @verifikator = Verifikator.new
  end

  # GET /verifikators/1/edit
  def edit
  end

  # POST /verifikators or /verifikators.json
  def create
    @verifikator = Verifikator.new(verifikator_params)

    respond_to do |format|
      if @verifikator.save
        format.html { redirect_to verifikator_url(@verifikator), notice: "Verifikator was successfully created." }
        format.json { render :show, status: :created, location: @verifikator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @verifikator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verifikators/1 or /verifikators/1.json
  def update
    respond_to do |format|
      if @verifikator.update(verifikator_params)
        format.html { redirect_to verifikator_url(@verifikator), notice: "Verifikator was successfully updated." }
        format.json { render :show, status: :ok, location: @verifikator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @verifikator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verifikators/1 or /verifikators/1.json
  def destroy
    @verifikator.destroy!

    respond_to do |format|
      format.html { redirect_to verifikators_url, notice: "Verifikator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verifikator
      @verifikator = Verifikator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def verifikator_params
      params.require(:verifikator).permit(:jenis_dokumen, :menu_aplikasi, :kondisi_data, :catatan, :rekomendasi, :aplikasi_id)
    end
  end

app/helpers/aplikasis_helper.rb
module AplikasisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/status_data_helper.rb
module StatusDataHelper
end

app/helpers/verifikators_helper.rb
module VerifikatorsHelper
end

app/views/aplikasis/_aplikasi.html.erb
<div class="col" id="<%= dom_id aplikasi %>" data-controller="">
  <div class="card h-100">
    <div class="card-body link-open"
         data-controller="visit"
         data-visit-url-value="<%= aplikasi_path(aplikasi) %>"
         data-action="click->visit#open">
      <h5 class="card-title"><%= aplikasi.nama %></h5>
      <p class="card-text"><% aplikasi.inspect %></p>
    </div>
    <div class="card-footer">
      <small class="text-muted"><%= aplikasi.alamat_web %></small>
      <p> 
      <div>
        
      <p>
       <strong>verifikator:</strong>  
        <%= aplikasi.verifikators %>
      </p>
      </div>
      </p>
    </div>
  </div>
</div>

app/views/aplikasis/_form.html.erb
<%= form_with(model: aplikasi) do |form| %>
  <% if aplikasi.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aplikasi.errors.count, "error") %> prohibited this aplikasi from being saved:</h2>

      <ul>
        <% aplikasi.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nama, class: 'form-label' %>
    <%= form.text_field :nama, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :alamat_web, class: 'form-label' %>
    <%= form.text_field :alamat_web, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :nama_penanggung_jawab, class: 'form-label' %>
    <%= form.text_field :nama_penanggung_jawab, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :deskripsi, class: 'form-label' %>
    <%= form.text_field :deskripsi, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :verifikator, class: 'form-label' %>
    <%= form.text_field :verifikator, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/aplikasis/create.turbo_stream.erb
<%= turbo_stream.append "aplikasis", @aplikasi %>
<%= turbo_stream.update "new_aplikasi", "" %>

app/views/aplikasis/edit.html.erb
<h1>Editing aplikasi</h1>

<%= render "form", aplikasi: @aplikasi %>

<br>

<div>
  <%= link_to "Show this aplikasi", @aplikasi %> |
  <%= link_to "Back to aplikasis", aplikasis_path %>
</div>

app/views/aplikasis/index.html.erb
<%= content_for :html_title, "Aplikasi" %>
<%= content_for :navigation do %>
  <li class="breadcrumb-item" aria-current="page">Home</li>
  <li class="breadcrumb-item active" aria-current="page">Aplikasi</li>
<% end %>
<div class="card border-0 shadow">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="fs-5 fw-bold mb-0">Aplikasi</h2>
        
      </div> 
      <div class="col text-end">
        <%= link_to "Aplikasi Baru",
            new_aplikasi_path,
            class: 'btn btn-primary',
            data: {
              turbo_frame: 'modal'
            } %>
      </div>
      <%= @app %>
    </div>
  </div>
  <div class="card-body">
    <div id="aplikasis" class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
      <%= render @aplikasis %>
    </div>
  </div>
</div>

app/views/aplikasis/new.html.erb
<main class="container">
  <%= turbo_frame_tag "modal" do %>
    <h1 class="h3 modal-header">
      Aplikasi Baru
    </h1>
    <div class="modal-body">
      <%= render "aplikasis/form", aplikasi: @aplikasi %>
    </div>
  <% end %>
</main>

app/views/aplikasis/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aplikasi %>

<div>
  <%= link_to "Edit this aplikasi", edit_aplikasi_path(@aplikasi) %> |
  <%= link_to "Back to aplikasis", aplikasis_path %>

  <%= button_to "Destroy this aplikasi", @aplikasi, method: :delete %>
</div>

app/views/layouts/_head_content.html.erb
<nav aria-label="breadcrumb" class="d-none d-md-inline-block mb-4">
  <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent mb-0">
    <li class="breadcrumb-item">
      <%= link_to root_path do %>
        <i class="bi bi-house-door-fill"></i>
      <% end %>
    </li>
    <%= yield :navigation %>
  </ol>
</nav>

app/views/layouts/_header.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="/">Kota Madiun</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="#">Sign out</a>
    </div>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse min-vh-100">
  <div class="position-sticky pt-3 sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to root_path, class: 'nav-link' do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home align-text-bottom" aria-hidden="true"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
          Dashboard
        <% end %>
      </li>
    </ul>
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
      <span>Master Data</span>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <%= link_to aplikasis_path, class: 'nav-link' do %>
          <i class="fa-solid fa-laptop-file me-2"></i>
          Aplikasi
        <% end %>
      </li>
    </ul>
    <ul class="nav flex-column mb-2">
    <li class="nav-item">
    <%= link_to verifikators_path, class: 'nav-link' do %>
      <i class="fa-solid fa-user-shield me-2"></i>
      Verifikator 
      <% end %>
      </li>
    </ul>
    <ul class="nav flex-column mb-2">
    <li class="nav-item">
    <%= link_to status_data_path, class: 'nav-link' do %>
      <i class="bi bi-envelope-fill me-2"></i>
      Status Data 
      <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:html_title) ? yield(:html_title) : "Monitoring" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" rel="stylesheet">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row">
        <%= render 'layouts/navbar' %>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 py-3">
          <%= render 'layouts/head_content' %>
          <%= yield %>
        </main>
      </div>
    </div>
    <%= render 'shareds/modal' %>
  </body>
</html>

app/views/shareds/_modal.html.erb
<div class="modal fade" tabindex="-1" aria-labelledby="modal" aria-hidden="true"
     data-controller="modal"
     data-action="turbo:frame-load->modal#open turbo:submit-end->modal#close"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <%= turbo_frame_tag "modal" %>
      </div>
    </div>
  </div>
</div>

app/views/status_data/_form.html.erb
<%= form_with(model: status_datum) do |form| %>
  <% if status_datum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(status_datum.errors.count, "error") %> prohibited this status_datum from being saved:</h2>

      <ul>
        <% status_datum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :kondisi_data, style: "display: block" %>
    <%= form.text_field :kondisi_data %>
  </div>

  <div>
    <%= form.label :catatan, style: "display: block" %>
    <%= form.text_field :catatan %>
  </div>

  <div>
    <%= form.label :rekomendasi, style: "display: block" %>
    <%= form.text_field :rekomendasi %>
  </div>

  <div>
    <%= form.label :validasi, style: "display: block" %>
    <%= form.text_field :validasi %>
  </div>

 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/status_data/_status_datum.html.erb
<div id="<%= dom_id status_datum %>">
  <p>
    <strong>Kondisi data:</strong>
    <%= status_datum.kondisi_data %>
  </p>

  <p>
    <strong>Catatan:</strong>
    <%= status_datum.catatan %>
  </p>

  <p>
    <strong>Rekomendasi:</strong>
    <%= status_datum.rekomendasi %>
  </p>

  <p>
    <strong>Validasi:</strong>
    <%= status_datum.validasi %>
  </p>

</div>

app/views/status_data/edit.html.erb
<h1>Editing status data</h1>

<%= render "form", status_datum: @status_datum %>

<br>

<div>
  <%= link_to "Show this status data", @status_datum %> |
  <%= link_to "Back to status data", status_data_path %>
</div>

app/views/status_data/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Status data</h1>

<div id="status_data">
  <% @status_data.each do |status_datum| %>
    <%= render status_datum %>
    <p>
      <%= link_to "Show this status data", status_datum %>
    </p>
  <% end %>
</div>

<%= link_to "New status data", new_status_datum_path %>

app/views/status_data/new.html.erb
<h1>New status data</h1>

<%= render "form", status_datum: @status_datum %>

<br>

<div>
  <%= link_to "Back to status data", status_data_path %>
</div>

app/views/status_data/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @status_datum %>

<div>
  <%= link_to "Edit this status data", edit_status_datum_path(@status_datum) %> |
  <%= link_to "Back to status data", status_data_path %>

  <%= button_to "Destroy this status data", @status_datum, method: :delete %>
</div>

app/views/verifikators/_form.html.erb
<%= form_with(model: verifikator) do |form| %>
  <% if verifikator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(verifikator.errors.count, "error") %> prohibited this verifikator from being saved:</h2>

      <ul>
        <% verifikator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :aplikasi, class: 'form-label' %>
  <%= form.select(:aplikasi_id, options_for_select(Aplikasi.pluck(:nama, :id), form.object.aplikasi), {},
  { data: {"placeholder": "Pilih Aplikasi",
            controller: 'dropdown',
            dropdown_parent_value: '#form-kelompok-anggaran'}
  }) %>
  </div>

  <div>
    <%= form.label :jenis_dokumen, style: "display: block" %>
    <%= form.text_field :jenis_dokumen %>
  </div>

  <div>
    <%= form.label :menu_aplikasi, style: "display: block" %>
    <%= form.text_field :menu_aplikasi %>
  </div>

  <div>
    <%= form.label :kondisi_data, style: "display: block" %>
    <%= form.text_field :kondisi_data %>
  </div>

  <div>
    <%= form.label :catatan, style: "display: block" %>
    <%= form.text_field :catatan %>
  </div>

  <div>
  <%= form.label :rekomendasi, style: "display: block" %>
  <%= form.text_field :rekomendasi %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/verifikators/_verifikator.html.erb
<div id="<%= dom_id verifikator %>">

  <p>
  <strong>Aplikasi:</strong>  
  <%= verifikator.aplikasi %>
  </p>

  <p>
    <strong>Jenis dokumen:</strong>
    <%= verifikator.jenis_dokumen %>
  </p>

  <p>
    <strong>Menu aplikasi:</strong>
    <%= verifikator.menu_aplikasi %>
  </p>

  <p>
    <strong>Kondisi data:</strong>
    <%= verifikator.kondisi_data %>
  </p>

  <p>
    <strong>Catatan:</strong>
    <%= verifikator.catatan %>
  </p>

  <p>
  <strong>Rekomendasi:</strong>
  <%= verifikator.rekomendasi %>
  </p>

</div>

app/views/verifikators/edit.html.erb
<h1>Editing verifikator</h1>

<%= render "form", verifikator: @verifikator %>

<br>

<div>
  <%= link_to "Show this verifikator", @verifikator %> |
  <%= link_to "Back to verifikators", verifikators_path %>
</div>

app/views/verifikators/index.html.erb
<%= content_for :html_title, "Verifikasi" %>
<%= content_for :navigation do %>
  <li class="breadcrumb-item" aria-current="page">Home</li>
  <li class="breadcrumb-item active" aria-current="page">
  <%= link_to 'verifikator', verifikators_url %>
  </li>
<% end %>
<p style="color: green"><%= notice %></p>

<h3>Verifikator</h3>

<p class= "new btn btn-sn">
<%= link_to "New verifikator", new_verifikator_path %>
</p>
<%= link_to "Download as CSV", verifikators_path(format: :csv) %>


<div id="verifikators">
  <% @verifikators.each do |verifikator| %>
    <%= render verifikator %>
    <p class="style btn btn-sn">
      <%= link_to "Show this verifikator", verifikator %>
    </p>
  <% end %>
</div>

app/views/verifikators/new.html.erb
<h1>New verifikator</h1>

<%= render "form", verifikator: @verifikator %>

<br>

<div>
  <%= link_to "Back to verifikators", verifikators_path %>
</div>

app/views/verifikators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @verifikator %>

<div>
  <%= link_to "Edit this verifikator", edit_verifikator_path(@verifikator) %> |
  <%= link_to "Back to verifikators", verifikators_path %>

  <%= button_to "Destroy this verifikator", @verifikator, method: :delete %>
</div>